// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED BY CUSTOM SHOELACE CLI
// Removing this comment will prevent it from being managed by the CLI.
// ---------------------------------------------------------------------

import LdIcon from './icon.component.js';
export * from './icon.component.js';
export default LdIcon;
LdIcon.define('ld-icon');
