// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED BY CUSTOM SHOELACE CLI
// Removing this comment will prevent it from being managed by the CLI.
// ---------------------------------------------------------------------

import LdAlert from './alert.component.js';
export * from './alert.component.js';
export default LdAlert;
LdAlert.define('ld-alert');
